---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
## Loading required package: viridisLite
library(p8105.datasets)

library(plotly)
```

```{r data_plot}
# set.seed(1)
# 
# data(nyc_airbnb)
# nyc_airbnb = 
#   nyc_airbnb %>% 
#   mutate(rating = review_scores_location / 2) %>%
#   select(boro = neighbourhood_group, neighbourhood, rating, price, room_type,
#          latitude, longitude) %>%
#   filter(!is.na(rating), 
#          boro == "Manhattan",
#          room_type == "Entire home/apt",
#          price %in% 100:500)  %>% 
#   sample_n(5000)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_airbnb %>%
 plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

### Chart C

```{r}

```

